version: '3'

services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9644/v1/status/ready"]
      start_period: 5s
      interval: 3s
    networks:
      - ch_ntw

  deephaven:
    container_name: deephaven
    build:
      context: deephaven
    environment:
      START_OPTS: -Xmx24g -Dio.deephaven.app.GcApplication.enabled=true
    ports:
      - "10000:10000"
    volumes:
      - ./data/deephaven:/data/storage
      - ./data/parquet:/data/parquet
    depends_on:
      redpanda:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - ch_ntw

  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./build/init_trades.sql:/docker-entrypoint-initdb.d/init_trades.sql:ro
      - ./build/init_orderbooks.sql:/docker-entrypoint-initdb.d/init_orderbook.sql:ro
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "-q", "localhost:8123/ping"]
      start_period: 5s
      interval: 3s
    networks:
        - ch_ntw

  cryptofeed:
    container_name: cryptofeed
    build:
      context: cryptofeed
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24